import { Request, Response } from "express";
import pool  from "../db/config";
import { OneDayPackageImpl } from "../models/OneDayPckgeC";
import { TwoDayPackageImpl } from "../models/SecondDayPckge";

// One-Day Package
export const addOneDayPackage = async (req: Request, res: Response) => {
  const {
    senderName,
    receiverName,
    senderAddress,
    receiverAddress,
    weight,
    costPerWeight,
    flatFee,
  } = req.body;

  const trackingNumber = Math.floor(100000 + Math.random() * 900000); // 6-digit

  const packageOneDay = new OneDayPackageImpl(
    0, // id (autogenerated by DB)
    senderName,
    receiverName,
    senderAddress,
    receiverAddress,
    weight,
    costPerWeight,
    "Created",
    trackingNumber.toString(),
    flatFee
  );

  try {
    const query = `
      INSERT INTO packages (
        senderName, receiverName, senderAddress, receiverAddress, 
        weight, costPerWeight, trackingNumber, flatFee, shippingMethod, status
      ) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
    `;

    await pool.query(query, [
      packageOneDay["senderName"],
      packageOneDay["receiverName"],
      packageOneDay["senderAddress"],
      packageOneDay["receiverAddress"],
      packageOneDay["weight"],
      packageOneDay["costPerWeight"],
      parseInt(packageOneDay["trackingNumber"]),
      flatFee,
      "One-Day",
      packageOneDay["status"],
    ]);

    res.status(201).json({ message: "One-Day Package added successfully" });
  } catch (error) {
    console.error(error);
    res.status(500).json({ message: "Error adding One-Day Package" });
  }
};

// Two-Day Package
export const addTwoDayPackage = async (req: Request, res: Response) => {
  const {
    senderName,
    receiverName,
    senderAddress,
    receiverAddress,
    weight,
    costPerWeight,
    flatFee,
  } = req.body;

  const trackingNumber = Math.floor(100000 + Math.random() * 900000); // 6-digit

  const packageTwoDay = new TwoDayPackageImpl(
    0,
    senderName,
    receiverName,
    senderAddress,
    receiverAddress,
    weight,
    costPerWeight,
    "Created",
    trackingNumber.toString(),
    flatFee
  );

  try {
    const query = `
      INSERT INTO packages (
        sendername, receivername, senderaddress, receiveraddress, 
        weight, costperweight, trackingnumber, flatfee, shippingmethod, status
      ) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
    `;

    await pool.query(query, [
      packageTwoDay["senderName"],
      packageTwoDay["receiverName"],
      packageTwoDay["senderAddress"],
      packageTwoDay["receiverAddress"],
      packageTwoDay["weight"],
      packageTwoDay["costPerWeight"],
      parseInt(packageTwoDay["trackingNumber"]),
      flatFee,
      "Two-Day",
      packageTwoDay["status"],
    ]);

    res.status(201).json({ message: "Two-Day Package added successfully" });
  } catch (error) {
    console.error(error);
    res.status(500).json({ message: "Error adding Two-Day Package" });
  }
};

export const getAllPackages = async (req: Request, res: Response) => {
    try {
        const result = await pool.query("SELECT * FROM packages");
        res.status(200).json(result.rows); 
    } catch (error) {
        console.error(error);
        res.status(500).json({ message: "Error fetching packages" });
    }
}

export const updatePackageStatus = async (req: Request, res: Response) => {
  const { trackingNumber } = req.params;
  const { status } = req.body;

  try {
    const query = "UPDATE packages SET status = $1, updatedAt = NOW() WHERE trackingNumber = $2";
    await pool.query(query, [status, trackingNumber]);

    res.status(200).json({ message: "Package status updated successfully" });
  } catch (error) {
    console.error("Error updating package status:", error);
    res.status(500).json({ message: "Error updating package status" });
  }
};
